### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by copie**
Add Chinese translation

### CODE REVIEW

**Comment by ZetaoYang** [comment]
@copie  good work!

**Comment by ZetaoYang** [comment]
@copie If possible, I hope you can also add Traditional Chinese translation.
Thanks for your contribution to such a great open source project.

**Comment by copie** [comment]
@ZetaoYang  I think I really want to do something wrong 
I can not use this ts file Make the application language into Chinese
I modified these codes
default
and i commit this code also as some problem like this
screenshot
miss some code
sorry 
The first time I submit a code to the community
It seems messed up
I am sorry

**Comment by lupoDharkael** [comment]
Don't worry, that line is just orientative for the translator. The translations seems to compile perfectly.
@ZetaoYang  can you confirm if it works?

**Comment by ZetaoYang** [comment]
@lupoDharkael compile perfectly and it works.

**Pull request merged**
