### PR TITLE
Add option to auto copy URL after upload

### PR DESCRIPTION
**Pull request by teryanik**
Hi!
I added option in config for auto copy link after upload
Issue #528 
image

I made it for prevent clicking on these buttons.
image

By default this options is disabled.
Thanks.

### CODE REVIEW

**Comment by Sphiinx** [comment]
@lupoDharkael :heart:

**Comment by rikosage** [comment]
Thanks you!

**Comment by Sphiinx** [comment]
Can this be merged please?

**Comment by lupoDharkael** [comment]
Looks good, Thanks!

**Comment by c1tru55** [comment]
@lupoDharkael please create new release with this PR and update packages, it is the only missing feature in the app!

**Pull request merged**
