### PR TITLE
Update russian translation

### PR DESCRIPTION
**Pull request by alok1111**
default
By the way, it would be nice to have an ability to translate "SPACEBAR" text.

### CODE REVIEW

**Comment by DaVukovic** [comment]
> By the way, it would be nice to have an ability to translate "SPACEBAR" text.

That's possible. At least I got it managed at my PR. Please take a look at:

https://github.com/DaVukovic/flameshot/blob/6d278c0fc7281de998e2f8a17b11659282b8b9d6/src/widgets/infowindow.cpp#L62

and then:

https://github.com/DaVukovic/flameshot/blob/6d278c0fc7281de998e2f8a17b11659282b8b9d6/translations/Internationalization_de_DE.ts#L401-L405

That should be exactly what you are searching for.

**Comment by alok1111** [comment]
> Hi! IMHO, it's shorter to make such translation.
> Показать панель с настройками выбранного инструмента
Дословно sidebar это всё-таки боковая панель

**Comment by greno4ka** [comment]
Yes, you're right, but first of all it doesn't matter sidebar it is or just panel. The second thing is, that it's quite long for that small window. Even english variant is not fully readable in default window, so you need to expand it to read about this feature. That takes a time. I don't insist on this change. Just suggested to think about it.

**Comment by lupoDharkael** [comment]
Thanks for the contribution!

**Pull request merged**
