### PR TITLE
snapcraft files added

### LINKED ISSUE #46: Add .deb or .snap for Ubuntu
If possible, please release this software for Ubuntu, it would be very useful for me as a developer.

### PR DESCRIPTION
**Pull request by hurricanehrndz**
This closes #46. This is an initial release of a snap version of flameshot. It is early days and there is some minor bugs that probably need to be addressed.

- [ ] System Tray Icons do not display
- [ ] Travis needs to be tied into [build.snapcraft.io for CI](https://tutorials.ubuntu.com/tutorial/continuous-snap-delivery-from-travis-ci#4)
- [ ] [Remove duplication of desktop files by implementing CMake perhaps](https://github.com/FreeRDP/Remmina/blob/next/snap/CMakeLists.txt).
- [ ] snap needs to be pushed to store or travis integration completed.

Other projects delivering QT apps through snaps for reference:
[mumble](https://github.com/snapcrafters/mumble)
[vlc](https://github.com/videolan/vlc/blob/061b1f0fe822468f549defd6a66da42f9e1f9506/extras/package/snap/snapcraft.yaml)

For testings purposes right now, you need the following:
lxc
snapd

To Test:
clone repo
cd to repo directory
snapcraft cleanbuild
sudo snap install flameshot_git_amd64.snap --dangerous --devmode

To use:
Run Launch-Flameshot 
Run Flameshot

### CODE REVIEW

**Comment by lupoDharkael** [comment]
Is this ready to merge?

**Comment by hurricanehrndz** [comment]
Yes, it works. Feedback is required.

**Comment by lupoDharkael** [comment]
About the desktop file duplication.
The only thing that changes in the desktop files is the `Icon` right? that would be easy to generate from the .pro
I could send you a PR  to your fork to add the changes.

**Comment by hurricanehrndz** [comment]
Yes that is correct and thank you. This is ready to be submitted to build.snapcraft.io in the dev channel, I figured since this is your project that you would want to do that yourself.

**Comment by lupoDharkael** [comment]
I'm merging so I can work in the repo to modify the generation of .desktop

**Pull request merged**
