### PR TITLE
Add german translation

### PR DESCRIPTION
**Pull request by DaVukovic**
As I received help here I thought it might be a good idea to give something back. 

Not a experienced developer at all, so please bear with me if you might find any issues. I'm absolutely not sure if the edits I've done for the CONTRIBUTING.md file are correct.

Please feel free to give any kind of feedback and I happily amend some edits

I tested this with Ubuntu 16.04 and 18.04 and AFAICT, I can't find anything missing.

### CODE REVIEW

**Comment by DaVukovic** [comment]
I'm not 100% sure, but I would say, the error is not related to my PR. Maybe @lupoDharkael could take a look.

**Comment by ZetaoYang** [comment]
@DaVukovic I‘m sure that's a problem of travisci.

**Comment by DaVukovic** [comment]
Thanks for answering. Thought so.

**Comment by AlfredoRamos** [comment]
It seems to be a timeout. You can close and re-open the this pull request to trigger the tests again.

**Comment by lupoDharkael** [comment]
I'll restart the build

**Comment by DaVukovic** [comment]
rebased and merge conflicts solved

**Comment by lupoDharkael** [comment]
The CI seems to be failing due to RPM errors. @ZetaoYang any idea?

**Comment by ZetaoYang** [comment]
@lupoDharkael @DaVukovic 

Appveyor error:
```
lrelease error: Cannot open translations/Internationalization_de.DE.ts: The system cannot find the file specified.
```
Name of `Internationalization_de.DE.ts` is not standard. (P.S. Why `_de.DE.` is?)

**Comment by DaVukovic** [comment]
Yeah, seen that already. Just haven't found the time. Most likely an error on my side. 

I'll let you know if I can solve it

Thanks for the heads up ;)

**Comment by DaVukovic** [comment]
Let's hope it was a typo only ;)

**Comment by ZetaoYang** [comment]
@DaVukovic @lupoDharkael It could be merged now.

**Comment by lupoDharkael** [comment]
Thanks!

**Pull request merged**
