### PR TITLE
Travis CI tests improvements

### LINKED ISSUE #213: Travis error notification
**Describe the bug**
The RPM build fails in travis and it isn't notified as a failed build.
```
PM build errors:
    Macro expanded in comment on line 59: %{name}.svg
    Macro expanded in comment on line 60: %{name}.svg
    File not found: /build/BUILDROOT/flameshot-0.5.1-1.fc27.x86_64/usr/share/applications/flameshot-init.desktop
    File not found: /build/BUILDROOT/flameshot-0.5.1-1.fc27.x86_64/usr/share/applications/flameshot-config.desktop
```
**Expected behavior**
A notification from Travis about a failed build.

### PR DESCRIPTION
**Pull request by AlfredoRamos**
This change aims to improve some logic in bash scripts, as well to make easier to maintain the installation of dependencies, build and deploy process.

Some highlights:

- Add `set -e` to bash scripts to exit immediately if a command exits with a non-zero status (Fixes #213)
- Move `.travis_linux.sh` to `travis/linux_script.sh`
- Move `.travis_macos.sh to travis/osx_script.sh`
- Use variable syntax `${var}` consistently
- Quote directory paths
- Split long commands into multiple lines
- Remove unneeded characters (`;`, `./`) and whitespaces
- Move `before_install` step instructions into a separate file
- Move `install` step instructions into a separate file

To maintain consistency, scripts are named using the following format:

```
<OS>_<step>.sh
```

### CODE REVIEW

**Comment by lupoDharkael** [comment]
I don't really understand why this one fails https://travis-ci.org/lupoDharkael/flameshot/jobs/386451095

OSX's build fails because I don't really support that platform but I could fix the compilation errors after the merge.

**Comment by lupoDharkael** [comment]
I don't think we should have osx in the CI, I refuse to maintain a version for Apple products. could you disable the build for that platform? maybe not delete the script but just disable the build job.

**Comment by ZetaoYang** [comment]
@AlfredoRamos @lupoDharkael  just comment them out.
```
 #      - os: osx
 #        compiler: clang
 #        osx_image: xcode9.2
```

**Comment by AlfredoRamos** [comment]
The only step that keeps failing is when running `source /opt/qt53/bin/qt53-env.sh` At this point I'm not sure if there's something wrong with that build or with the scripts.

I will investigate about that script.

**Comment by ZetaoYang** [comment]
@AlfredoRamos It succeed.

**Comment by AlfredoRamos** [comment]
@ZetaoYang Finally! :joy: 

Apparently there's a problem using `source`, I had to download `qt53base` deb to export the same environment variables.

https://github.com/travis-ci/travis-ci/issues/7472

@lupoDharkael @ZetaoYang Sorry if you got spammed with emails about failing tests, it won't happen again.

P.S.: I don't think is related, but it would be good if somebody could check if #223 was somehow related with the failing test, I don't use Ubuntu.

**Pull request merged**
