### PR TITLE
Add instructions for global keyboard shortcuts

### PR DESCRIPTION
**Pull request by giogziro95**
Only for KDE Plasma at this point.

### CODE REVIEW

**Comment by lupoDharkael** [comment]
I think it would be better to have a copy of that file inside the repo.
Maybe in ./docs/shortcuts-config/

**Comment by giogziro95** [comment]
Okay, I'll create a new PR.

**Comment by lupoDharkael** [comment]
If you add a new commit to your cloned repo, it will be added to this PR. You don't need to create a new one.

**Comment by giogziro95** [comment]
Sorry, you are right. I totally forgot that. 😀

**Comment by giogziro95** [comment]
I think it's much better now.

**Comment by giogziro95** [comment]
@lupoDharkael Hey! Is there anything else I can do?

**Comment by lupoDharkael** [comment]
The changes look good! I'll try to review them tomorrow.

**Pull request merged**
