### PR TITLE
Misc. source comment typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -i 3 -w -S ./translations -L uint,exten -C 3`

### CODE REVIEW

**Comment by hosiet** [comment]
Hi @luzpaz, I believe this project is already dead and your pull request will likely not be handled.

Could you consider submitting your fix onto the forked nixnote2 project https://github.com/robert7/nixnote2 ?

**Comment by luzpaz** [comment]
flameshot is dead ???

**Comment by hosiet** [comment]
Oooops my fault. I just mixed two of my contributed projects up.

Please ignore my comment...

**Comment by hosiet** [comment]
BTW `auxiliar` doesn't look like a typo. It still fits English grammar though `codespell` does emits some sort of warnings.

**Comment by luzpaz** [comment]
It's considered [archaic](https://en.wiktionary.org/wiki/auxiliar) and superseded by `auxiliary`

**Comment by lupoDharkael** [comment]
thanks for the contribution!

**Pull request merged**
