### PR TITLE
Fixup working with startupLaunch value

### PR DESCRIPTION
**Pull request by greno4ka**
This commit fixes problem, when you want to import or export
information about startup.

So now program can write this value to settings, and then, when it will read it, it first of all analyses if settings value corresponds to file existence, and corrects the situation according to settings' value.

### CODE REVIEW

**Comment by greno4ka** [comment]
So, @lupoDharkael, can you regard this feature?

**Comment by greno4ka** [comment]
I just noticed, that on clean system, `.config/autostart` can be absent. So the second commit is about verifying the existence of this dir and it's creation, if nessesary. This can be related with many issues about autostart problems.

**Comment by greno4ka** [comment]
Travis has error, not tied with my contribution.

curl: (35) gnutls_handshake() failed: Error in the pull function.
The command "curl --upload-file dist/flameshot_0.6.0_fedora27_x86_64.rpm https://transfer.sh/flameshot_0.6.0_fedora27_x86_64.rpm" failed 3 times.

**Comment by lupoDharkael** [comment]
I'm reviewing this tomorrow (sorry for the wait but lately it's hard for me to take time).

**Comment by greno4ka** [comment]
No problem, @lupoDharkael.

**Comment by lupoDharkael** [comment]
Seems right to me. Thanks!

**Pull request merged**
